name: Monitor SEC company reports

on:
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * *"

permissions:
  contents: write

jobs:
  update:
    uses: ./.github/workflows/data-pipeline.yml
    with:
      mode: "sec"
    secrets: inherit
